### ISSUE TITLE
Lifetime question

### ISSUE THREAD

**Issue by wiiznokes** [koutheir/lm-sensors#2]
Sorry if this is a dumb question, i'm kinda new to Rust.

I want to create a Vec of a struct to control some Sensors. So I filter the `SubFeatureRef` im interested in. But i'm confuse about the lifetime of this ref. does it  going to drop when `let sensors = lm_sensors::Initializer::default().initialize().unwrap();` is drop ? or after the process terminate ? So can i use 'static lifetime safely on my struct ?

**Comment by koutheir** [comment]
> Sorry if this is a dumb question, i'm kinda new to Rust.

No problem. We're all learning.

> I want to create a Vec of a struct to control some Sensors. So I filter the SubFeatureRef im interested in.

Sharing some code illustrating how you're doing this might make it easier to help you.

> But i'm confuse about the lifetime of this ref.

The lifetime `'a` of a [`SubFeatureRef<'a>`](https://docs.rs/lm-sensors/latest/lm_sensors/struct.SubFeatureRef.html) is the lifetime of the [`LMSensors`](https://docs.rs/lm-sensors/latest/lm_sensors/struct.LMSensors.html) instance returned by [`Initializer::initialize()`](https://docs.rs/lm-sensors/latest/lm_sensors/struct.Initializer.html#method.initialize). The use of `'a` makes sure that `libsensors` is properly initialized, and remains loaded, when its APIs are used through this crate.

> does it going to drop when let sensors = lm_sensors::Initializer::default().initialize().unwrap(); is drop ?

As long as you keep the `LMSensors` instance alive, you can use your `SubFeatureRef<'a>` instances. If you want to drop your `LMSensors` instance for some reason, then you have to make sure all instances that use `'a` are already out of scope too, otherwise the compiler will complain that your `LMSensors` instance doesn't live long enough.

> or after the process terminate ? So can i use 'static lifetime safely on my struct ?

If you want to use the sensors until the process terminates, then you can store it on the heap using [`Box::new()`](https://doc.rust-lang.org/std/boxed/struct.Box.html#method.new), then leak it indefinitely using [`Box::leak()`](https://doc.rust-lang.org/std/boxed/struct.Box.html#method.leak). Just make sure to ask `Box::leak()` to produce a mutable reference with the `'static` lifetime. If you do this, then `'a` above will equal `'static`.

If you're not sure for how long you'll need to use your `LMSensors` instance, then consider storing it behind an `Rc` or `Arc`.

**Comment by wiiznokes** [comment]
Thanks for this response, this is very clear. It's hard to provide a sample because nothing compile for now., i wanted to abstract the use of lm-sensors with generic but i get multitude of errors

**Comment by koutheir** [comment]
OK. I'll close the issue for now. Feel free to reopen it as needed if new concerns arise.

**Comment by wiiznokes** [comment]
Hi, i managed to clean up my code a bit. I get errors with lifetime while using lm_sensor, so maybe you could help me :sweat_smile: 

So here is my code:

A trait `Generator`. It will store `LMSensors` and generate temps.
```rust
pub trait Generator<'a> {


    fn new() -> impl Generator<'a> where Self: Sized;


    fn temps(&self) -> Vec<Box<Temp<'a>>>;
}
```

And the Linux implementation:

```rust
pub struct LinuxGenerator {
    sensors: LMSensors,
}


impl<'a> Generator<'a> for LinuxGenerator {

    fn new() -> impl Generator<'a> {
        // Initialize LM sensors library.
        let sensors = lm_sensors::Initializer::default().initialize().unwrap();

        Self { sensors }
    }

 

    fn temps(&self) -> Vec<Box<Temp<'a>>> {
        let mut temps:Vec<Box<Temp<'a>>> = Vec::new();

        for chip_ref in self.sensors.chip_iter(None) {
            if let Some(path) = chip_ref.path() {
                println!("chip: {} at {} ({})", chip_ref, chip_ref.bus(), path.display());
            } else {
                println!("chip: {} at {}", chip_ref, chip_ref.bus());
            }

            for feature_ref in chip_ref.feature_iter() {
                if feature_ref.kind() != Some(Kind::Temperature) {
                    continue;
                }

                let Some(Ok(name)) = feature_ref.name() else {
                    continue;
                };

                let Ok(sub_feature_ref) =
                    feature_ref.sub_feature_by_kind(lm_sensors::value::Kind::FanInput)
                else {
                    continue;
                };
                    

                let linux_temp = LinuxTemp {
                    chip_ref: chip_ref.clone(),
                    feature_ref,
                    sub_feature_ref,
                };
                
                let temp: Temp<'a> = Temp {
                    name: name.to_string(),
                    hardware_temp: Some(linux_temp)
                    
                };
                temps.push(Box::new(temp))
            }
        }
        temps
    }

  
}

#[derive(Debug, Clone)]
pub struct LinuxTemp<'a> {

    chip_ref: ChipRef<'a>,

    feature_ref: FeatureRef<'a>,

    pub sub_feature_ref: SubFeatureRef<'a>,

}
```


And this is the error message i get:

```shell
error[E0597]: `chip_ref` does not live long enough
  --> src/sensors/lm_sensors.rs:39:32
   |
18 | impl<'a> Generator<'a> for LinuxGenerator {
   |      -- lifetime `'a` defined here
...
32 |         for chip_ref in self.sensors.chip_iter(None) {
   |             -------- binding `chip_ref` declared here
...
39 |             for feature_ref in chip_ref.feature_iter() {
   |                                ^^^^^^^^ borrowed value does not live long enough
...
61 |                 let temp: Temp<'a> = Temp {
   |                           -------- type annotation requires that `chip_ref` is borrowed for `'a`
...
68 |         }
   |         - `chip_ref` dropped here while still borrowed

error[E0597]: `feature_ref` does not live long enough
  --> src/sensors/lm_sensors.rs:49:21
   |
18 | impl<'a> Generator<'a> for LinuxGenerator {
   |      -- lifetime `'a` defined here
...
39 |             for feature_ref in chip_ref.feature_iter() {
   |                 ----------- binding `feature_ref` declared here
...
49 |                     feature_ref.sub_feature_by_kind(lm_sensors::value::Kind::FanInput)
   |                     ^^^^^^^^^^^ borrowed value does not live long enough
...
61 |                 let temp: Temp<'a> = Temp {
   |                           -------- type annotation requires that `feature_ref` is borrowed for `'a`
...
67 |             }
   |             - `feature_ref` dropped here while still borrowed

error: lifetime may not live long enough
  --> src/sensors/lm_sensors.rs:61:27
   |
18 | impl<'a> Generator<'a> for LinuxGenerator {
   |      -- lifetime `'a` defined here
...
29 |     fn temps(&self) -> Vec<Box<Temp<'a>>> {
   |              - let's call the lifetime of this reference `'1`
...
61 |                 let temp: Temp<'a> = Temp {
   |                           ^^^^^^^^ type annotation requires that `'1` must outlive `'a`
```


I don't understand why `chip_ref` and `feature_ref` are dropped since i store them in `LinuxTemp` struct, with an explicit Lifetime, so my guess is they should be borrowed by `LinuxTemp` struct.

**Comment by wiiznokes** [comment]
Seems like `chip_ref.feature_iter()` and `feature_ref.sub_feature_by_kind` borrow `self`, but they takes `&self` in argument, i don't understand @koutheir

**Comment by wiiznokes** [comment]
hum nevermind, i confused borrowed and owned. But I still haven't managed to store a `SubFeatureRef` tho

**Comment by koutheir** [comment]
You should be able to store an instance of `SubFeatureRef<'a>` in a `struct X<'a>`. This makes sure one cannot use the struct instances after the `LMSensors` instance is dropped.

**Comment by wiiznokes** [comment]
Hum, sorry but could you provide a simple example? Even with a simple function, i can't store a Sub Feature Ref.

```rust
use lm_sensors::{prelude::SharedChip, LMSensors, SubFeatureRef};

struct X<'a> {
    sub_feature_ref: SubFeatureRef<'a>,
}

fn get_temps<'a>(sensors: &'a LMSensors) -> Vec<X<'a>> {
    let mut temps = Vec::new();

    for chip_ref in sensors.chip_iter(None) {
        for feature_ref in chip_ref.feature_iter() {
            if let Ok(sub_feature_ref) =
                feature_ref.sub_feature_by_kind(lm_sensors::value::Kind::FanInput)
            {
                temps.push(X { sub_feature_ref });
            }
        }
    }
    temps
}

fn main() {
    let sensors = lm_sensors::Initializer::default().initialize().unwrap();

    let _temps: Vec<X<'_>> = get_temps(&sensors);
}

```

```bash
error[E0515]: cannot return value referencing local variable `chip_ref`
  --> src/main.rs:19:5
   |
11 |         for feature_ref in chip_ref.feature_iter() {
   |                            -------- `chip_ref` is borrowed here
...
19 |     temps
   |     ^^^^^ returns a value referencing data owned by the current function

error[E0515]: cannot return value referencing local variable `feature_ref`
  --> src/main.rs:19:5
   |
13 |                 feature_ref.sub_feature_by_kind(lm_sensors::value::Kind::FanInput)
   |                 ----------- `feature_ref` is borrowed here
...
19 |     temps
   |     ^^^^^ returns a value referencing data owned by the current function

For more information about this error, try `rustc --explain E0515`.
error: could not compile `lm_test` (bin "lm_test") due to 2 previous errors

```

**Comment by koutheir** [comment]
I think your sample just uncovered a bug in dealing with certain references in the crate. I'll try to figure it out and fix it.

**Comment by koutheir** [comment]
@wiiznokes, can you please try out your example above with the version `0.2` of the crate?

Unfortunately, I had to make multiple breaking changes in order to correct the issue you discovered.

**Comment by wiiznokes** [comment]
Yeah this works great now thanks!
