### ISSUE TITLE
pattern to store SubFeatureRef in a struct

### ISSUE THREAD

**Issue by wiiznokes** [koutheir/lm-sensors#4]
I'm having trouble to store `SubFeatureRef` in a struct. This is my code:

```rust
use lm_sensors::{SubFeatureRef, value, LMSensors};

pub struct X<'a> {
    lib: LMSensors,
    v: Vec<SubFeatureRef<'a>>
}

impl <'a>X<'a> {
    
    pub fn new() -> Self {
        let lib = lm_sensors::Initializer::default().initialize().unwrap();
        let mut v = Vec::new();

        for chip_ref in lib.chip_iter(None) {
            for feature_ref in chip_ref.feature_iter() {
                if let Ok(sub_feature_ref) =
                    feature_ref.sub_feature_by_kind(value::Kind::FanInput) {
                        v.push(sub_feature_ref)
                }
            }
        }

        X {
            lib,
            v
        }
    }
}

fn main() {
    let _x = X::new();
}

```

The point of doing it this way it to hide `lm_sensors` behind the `X` struct. So i can't expose anythings referring to `lm_sensors` in the api.

Is there a way of doing that or is it just impossible? :sob:

**Comment by koutheir** [comment]
This is the classic Rust problem of a self-referencing structure. In `X` above, each element of `X.v`, (e.g., `X.v[0]`) has a reference to `X.lib`, and that reference must live less than `X.lib`. However, given the semantics of structures, all fields live the same duration, and the order of initialization and dropping of the fields is unspecified.

Solving this issue usually requires making the structure address stable, through `Pin`ning it, and controlling the order of initialization and drop of the structure instances, and using `unsafe` blocks. For a crate that can ease this burden, checkout [ouroboros](https://crates.io/crates/ouroboros).

If you can avoid the issue altogether, for example, by storing the `LMSensors` instance on the heap and `Box::leak`ing a `'static` reference to it, then you can store references to it inside a `Vec<SubFeatureRef<'static>>`. However, you must manually ensure that all these references are dropped before you drop the `LMSensors` instance on the heap (if you ever need to do so).

**Comment by wiiznokes** [comment]
Thank you for pointing out the problem to me. I chose to put a `'static` reference on my struct, since my program was going to do it in all cases. Here is my code, it compiles fine:

```rust
use lm_sensors::{value, LMSensors, SubFeatureRef};

pub struct X {
    lib: &'static LMSensors,
    v: Vec<SubFeatureRef<'static>>,
}

impl Drop for X {
    fn drop(&mut self) {
        let boxed = Box::new(self.lib);
        let ptr = Box::into_raw(boxed);
        unsafe {
            let _raw = Box::from_raw(ptr);
        }
    }
}

impl X {
    pub fn new() -> Self {
        let lib = lm_sensors::Initializer::default().initialize().unwrap();
        let boxed = Box::new(lib);
        let leaked: &'static mut LMSensors = Box::leak(boxed);

        let mut v = Vec::new();

        for chip_ref in leaked.chip_iter(None) {
            for feature_ref in chip_ref.feature_iter() {
                if let Ok(sub_feature_ref) = feature_ref.sub_feature_by_kind(value::Kind::FanInput)
                {
                    v.push(sub_feature_ref)
                }
            }
        }

        X { lib: leaked, v }
    }
}

fn main() {
    let _x = X::new();
}
```
I hope I did things right and didn't produce memory leak

**Comment by koutheir** [comment]
There are multiple issues with this code:
1. Your attempt at dropping the `'static LMSensors` instance does nothing.
2. Dropping the `'static LMSensors` instance means that the elements of `X.v` now refer to a dropped object. If the `Drop` implementation of `SubFeatureRef` refers to the `'static LMSensors` instance (yes, it can) then your program will probably crash.

A solution for (1) is to simply call `unsafe { Box::from_raw(self.lib) }` inside `X.drop()`.

A solution for (2) is to control the order of dropping of the fields of `X`, in order to ensure the following holds true:
> All fields holding references to the `'static LMSensors` instance must be dropped **BEFORE** the `'static LMSensors` instance itself.

In this situation, `X.v` must be dropped before `X.lib`. Wrap the fields in `ManuallyDrop` in order to control this.

**Comment by wiiznokes** [comment]
Ok so here is my `drop` function now:

```rust
impl Drop for X {
    fn drop(&mut self) {
        for sensor in &mut self.v {
            unsafe { ManuallyDrop::drop(sensor) };
        }
    }
}
```
> A solution for (1) is to simply call unsafe { Box::from_raw(self.lib) } inside X.drop()

I can't call ` Box::from_raw(self.lib)`, it get a type error, and with `&mut` before, i get a seg fault.

look like `Box::leak` and `Box::from_raw` are not meant no be use together: https://users.rust-lang.org/t/can-box-leak-be-complemented-with-box-from-raw/64478

**Comment by koutheir** [comment]
> I can't call  Box::from_raw(self.lib), it get a type error

Right, I forgot that `Box::from_raw` needs a mutable pointer.

> and with &mut before, i get a seg fault.

Because a mutable reference must not be shared between the elements of `X.v`.

You'll have to drop `X.lib` outside of `X`, by the code that owns the `X` instance. But it's a weird thing to ask for the owner of `X` to clean up after `X` is used:

```rust
use lm_sensors::{value, LMSensors, SubFeatureRef};

pub struct X {
    lib: &'static LMSensors,
    v: Vec<SubFeatureRef<'static>>,
}

// This is useless, because `Vec` will do it.
// impl Drop for X {...}

impl X {
    pub fn new() -> Self {
        let lib = lm_sensors::Initializer::default().initialize().unwrap();
        let boxed = Box::new(lib);
        let leaked: &'static mut LMSensors = Box::leak(boxed);

        let mut v = Vec::new();

        for chip_ref in leaked.chip_iter(None) {
            for feature_ref in chip_ref.feature_iter() {
                if let Ok(sub_feature_ref) = feature_ref.sub_feature_by_kind(value::Kind::FanInput)
                {
                    v.push(sub_feature_ref)
                }
            }
        }

        X { lib: leaked, v }
    }

    pub fn dont_forget_to_call_me_or_i_will_leak(self) {
        let lib = self.lib; // Keep the shared reference.
        drop(self); // Drop all objects keeping a reference to lib, making it now our exclusive reference.
        // Drop our, now, exclusive reference.
        drop(unsafe { Box::from_raw(lib as *const LMSensors as *mut LMSensors) })
    }
}

fn main() {
    let x = X::new();
    x.dont_forget_to_call_me_or_i_will_leak();
}
```

That's why people use a crate, such as [ouroboros](https://crates.io/crates/ouroboros), to solve this common issue.

**Comment by wiiznokes** [comment]
I finally managed to setup `ouroboros` (I had actually tried before going to `'static`), because it's just impossible to call `free` on all execution paths.

Here is my code:

```rust
use lm_sensors::{value, LMSensors, SubFeatureRef};
use ouroboros::self_referencing;

#[self_referencing]
pub struct X {
    lib: LMSensors,
    #[borrows(lib)]
    #[not_covariant]
    v: Vec<SubFeatureRef<'this>>,
}

impl X {
    pub fn contruct() -> Self {
        XBuilder {
            lib: lm_sensors::Initializer::default().initialize().unwrap(),
            v_builder: |lib_from_struct: &LMSensors|{
                let mut v = Vec::new();

                for chip_ref in lib_from_struct.chip_iter(None) {
                    for feature_ref in chip_ref.feature_iter() {
                        if let Ok(sub_feature_ref) = feature_ref.sub_feature_by_kind(value::Kind::FanInput)
                        {
                            v.push(sub_feature_ref)
                        }
                    }
                }
                v
            },
        }.build()
    }
}

fn main() {
    let _x = X::contruct();
}
```

So if I understand correctly, this piece of code should not cause the memory leak?

**Comment by koutheir** [comment]
> So if I understand correctly, this piece of code should not cause the memory leak?

I think so. I tried it in a debugger and `LMSensors::drop()` is called correctly when `X` is dropped.

**Comment by wiiznokes** [comment]
Alright thanks a lot for your help
